package com.usta.edu.co.MedicineRotationManager.enumerations;

public enum HospitalLocation {
    OTHER,
    HOSPITAL_UNIVERSITARIO,
    CLINICA_PRIVADA,
    CENTRO_SALUD,
    HOSPITAL_REGIONAL,
    HOSPITAL_LOCAL,
    INSTITUTO_ESPECIALIZADO,
    CENTRO_ATENCION_PRIMARIA,
    HOSPITAL_PEDIATRICO,
    HOSPITAL_MATERNIDAD,
    CLINICA_ESPECIALIZADA,
    LABORATORIO_CLINICO,
    CENTRO_IMAGENOLOGIA,
    HOSPITAL_MILITAR,
    CENTRO_REHABILITACION
}
