package com.usta.edu.co.MedicineRotationManager.enumerations;

public enum TypeRotation {
    OTHER,
    MEDICINA_INTERNA,
    CIRUGIA_GENERAL,
    PEDIATRIA,
    GINECOLOGIA_OBSTETRICIA,
    URGENCIAS,
    CARDIOLOGIA,
    DERMATOLOGIA,
    NEUROLOGIA,
    PSIQUIATRIA,
    TRAUMATOLOGIA,
    OFTALMOLOGIA,
    OTORRINOLARINGOLOGIA,
    ANESTESIOLOGIA,
    RADIOLOGIA,
    MEDICINA_FAMILIAR,
    CUIDADOS_INTENSIVOS,
    ONCOLOGIA,
    NEFROLOGIA,
    ENDOCRINOLOGIA,
    GASTROENTEROLOGIA,
    REUMATOLOGIA,
    NEUMOLOGIA,
    HEMATOLOGIA,
    INFECTOLOGIA
}
