spring.application.name=MedicineRotationManager
spring.datasource.url=jdbc:mysql://bk1m3imwj6mzhlg9kjwi-mysql.services.clever-cloud.com:3306/bk1m3imwj6mzhlg9kjwi
spring.datasource.username=ubdjqwn2txlb3mlc
spring.datasource.password=xofsdHWDT2fWg9LsyGa6

jwt.secret-key =gU74vP9gkLmR2hnQxY4&zBwA1ytVcF8tjDhS6edeNxO3tqLyI0fpZbT52
jwt.expiration =86400000
jwt.refresh =172800000